server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://49.235.141.168:3306/mysql?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-wait-millis: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

##配置mybatis映射
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mysonandme.pojo
  ##类型处理器
  ##type-handlers-package:

##配置pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: false

##配置日志
logging:
  config: classpath:log4j2.xml

#配置redis
redis:
  # redis运行模式: standard-alone(单节点)/master-slave(主从模式)/cluster(集群模式)/sentinel(主从+哨兵模式)
  runMode: standard-alone
  # master节点名称(sentinel模式下可用)
  clusterName: mymaster
  # redis的地址信息，使用地址:端口方式隔离，如果是集群模式，多个地址间用,分隔
  # 单节点和主从模式的配置，只配置单节点/主节点的IP:PORT
  addr: 49.235.141.168:6379
  # 集群环境配置，需要将集群所有节点都配上(一般来说最少配置6个地址)
  #addr: 192.168.137.13:7001,192.168.137.13:7002,192.168.137.13:7003,192.168.137.14:7004,192.168.137.14:7005,192.168.137.14:7006
  # 主从+哨兵环境配置，配置哨兵地址即可
  #addr: 11.18.15.84:20001,11.18.22.30:20002,11.18.15.83:20003
  # Redis密码
  auth: redis
  # 连接池最大连接数（使用负值表示没有限制）
  maxTotal: 5
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  maxWaitMillis: -1
  # 连接池的最大空闲连接数
  maxIdle: 10
  # 连接池最小空闲连接数
  minIdle: 0
  # 连接的最小空闲时间 默认1800000毫秒(30分钟)
  minEvictableIdleTimeMillis: 300000
  # 每次释放连接的最大数目,默认3
  numTestsPerEvictionRun: 3
  # 逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  timeBetweenEvictionRunsMillis: 30000
  # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testOnBorrow: true
  # 在空闲时检查有效性, 默认false
  testWhileIdle: true
  # 连接超时时间
  timeout: 20000